import { useNavigate } from "react-router-dom";
import { Clock, MessageSquareText, Pencil, Route, Settings, X } from "lucide-react";
import sparkle from "/campaign-assets/ic-sparkle-ai.gif";
import JourneyStatusBadge from "./JourneyStatusBadge";

/**
 * Journey Builder header / L1 actions bar (Figma node 16788:23367).
 * Row 1: journey icon + name + primary actions (Save, Activate, close).
 * Row 2: status + meta (ID, dates, last edited) + Journey Goal / Settings /
 * comment / history. House font Manrope stands in for Figma's Nunito Sans.
 */
export default function JourneyBuilderHeader({
  name = "Cart_Abandonment_Festive_Season",
  created = true,
  generatedByAI = false,
  onActivate,
  onEditObjective,
}: {
  name?: string;
  /**
   * Whether a journey actually exists yet. Until one is created (e.g. the AI
   * drawer is still open over an empty canvas), the header shows an "Untitled"
   * placeholder with no ID / schedule meta.
   */
  created?: boolean;
  /** Shows a "Generated by AI" badge before the primary actions. */
  generatedByAI?: boolean;
  /** Called with the journey name when "Activate journey" is tapped. */
  onActivate?: (name: string) => void;
  /**
   * Called when the "Objective" button is tapped (AI journeys only) — reopens
   * the objective drawer so the goal can be changed and the journey regenerated.
   */
  onEditObjective?: () => void;
}) {
  const navigate = useNavigate();
  const displayName = created ? name : "Untitled";

  return (
    <header className="flex flex-col gap-2 rounded-lg bg-white px-10 py-2 shadow-[0px_5px_10px_0px_rgba(23,23,58,0.05)]">
      {/* Row 1 — title + primary actions */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <span className="grid place-items-center rounded-[5px] bg-[#F7E8FD] p-1.5">
            <Route className="h-6 w-6 text-[#BE52F2]" strokeWidth={1.9} />
          </span>
          <h1 className={`font-manrope text-[20px] font-bold tracking-[0.42px] ${created ? "text-[#17173A]" : "text-[#6F6F8D]"}`}>
            {displayName}
          </h1>
        </div>

        <div className="flex items-center gap-4">
          {generatedByAI && (
            <span className="flex items-center gap-1.5 rounded-full border border-[#C9D7F5] bg-[#E7EDFF] px-3 py-1.5 font-manrope text-xs font-semibold tracking-[0.2px] text-[#2F68E5]">
              <img src={sparkle} alt="" className="h-4 w-4" />
              Generated by AI
            </span>
          )}
          <button className="rounded border-[1.5px] border-[#143F93] bg-white px-[18px] py-2 font-manrope text-sm font-semibold uppercase tracking-[0.42px] text-[#143F93] transition-colors hover:bg-[#F3F6FF]">
            Save
          </button>
          <button
            onClick={() =>
              onActivate
                ? onActivate(displayName)
                : navigate("/journeys", {
                    state: { activatedJourney: { name: displayName, generatedByAI } },
                  })
            }
            className="rounded bg-[#143F93] px-[18px] py-2 font-manrope text-sm font-semibold uppercase tracking-[0.42px] text-white transition-colors hover:bg-[#0f3277]"
          >
            Activate journey
          </button>
          <button
            aria-label="Close"
            onClick={() => navigate("/journeys")}
            className="grid h-9 w-9 place-items-center rounded border-[1.5px] border-[#DDE2EE] bg-white text-[#6F6F8D] transition-colors hover:bg-[#F3F6FF]"
          >
            <X className="h-5 w-5" strokeWidth={1.9} />
          </button>
        </div>
      </div>

      <div className="h-px w-full bg-[#DDE2EE]" />

      {/* Row 2 — status + meta + secondary actions */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <JourneyStatusBadge status={created ? "STOPPED" : "DRAFT"} />
          {created && (
            <div className="flex items-center gap-2 font-manrope text-sm font-semibold tracking-[0.42px] text-[#6F6F8D]">
              <span>ID: 5115</span>
              <span className="h-4 w-px bg-[#DDE2EE]" />
              <span>Start - End date: Oct 16, 2025 10:40 AM - Never ending</span>
              <span className="h-4 w-px bg-[#DDE2EE]" />
              <span>Last edited: Nov 13, 2025 12:16 PM</span>
            </div>
          )}
        </div>

        <div className="flex items-center gap-4">
          <button
            onClick={generatedByAI ? onEditObjective : undefined}
            className="flex items-center gap-1 rounded border border-[#DDE2EE] bg-white px-3.5 py-1.5 font-manrope text-sm font-semibold uppercase tracking-[0.42px] text-[#6F6F8D] transition-colors hover:bg-[#F3F6FF]"
          >
            <Pencil className="h-3.5 w-3.5" strokeWidth={1.9} />
            {generatedByAI ? "Objective" : "Journey goal"}
          </button>
          <button className="flex items-center gap-1 rounded border border-[#DDE2EE] bg-white px-3.5 py-1.5 font-manrope text-sm font-semibold uppercase tracking-[0.42px] text-[#6F6F8D] transition-colors hover:bg-[#F3F6FF]">
            <Settings className="h-3.5 w-3.5" strokeWidth={1.9} />
            Settings
          </button>
          <span className="h-6 w-px bg-[#DDE2EE]" />
          <button
            aria-label="Comments"
            className="grid h-7 w-7 place-items-center rounded border border-[#DDE2EE] bg-white text-[#6F6F8D] transition-colors hover:bg-[#F3F6FF]"
          >
            <MessageSquareText className="h-4 w-4" strokeWidth={1.9} />
          </button>
          <button
            aria-label="History"
            className="grid h-7 w-7 place-items-center rounded border border-[#DDE2EE] bg-white text-[#6F6F8D] transition-colors hover:bg-[#F3F6FF]"
          >
            <Clock className="h-4 w-4" strokeWidth={1.9} />
          </button>
        </div>
      </div>
    </header>
  );
}
